version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:v1
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - application
    container_name: api
    tty: true

networks:
  application:
    driver: bridge
